FROM ubuntu:jammy AS stage_build

RUN apt-get -qq -y update \
    && apt-get -qq install -y --no-install-recommends \
        binutils \
        build-essential \
        ca-certificates \
        file \
        git \
        python3 \
        python3-pip \
        cmake

RUN apt-get -y install wget

WORKDIR /emsdk
ARG EMSDK_VERSION=4.0.12

RUN git clone --depth 1 --branch ${EMSDK_VERSION} https://github.com/emscripten-core/emsdk.git /emsdk


RUN ./emsdk install ${EMSDK_VERSION}

RUN ./emsdk install binaryen-main-64bit

# need newer node for JSPI
RUN sed -i 's/22\.16\.0/24.6.0/g' scripts/update_node.py emsdk_manifest.json
RUN wget -O node.tar.xz https://nodejs.org/dist/v24.6.0/node-v24.6.0-linux-x64.tar.xz && \
    rm -rf node/* && \
    tar xvf node.tar.xz -C node && \
    mv node/node-v24.6.0-linux-x64 node/24.6.0-linux-x64 && \
    rm node.tar.xz


COPY ./libasync.js upstream/emscripten/src/lib

# RUN cd /emsdk/binaryen/main_64bit_binaryen/ && sh recmake.sh

RUN cd /emsdk/binaryen/main_64bit_binaryen/ && cmake --build . --config Release -- -j4
RUN bash -c "chown -R 1000:1000 binaryen/main_64bit_binaryen/{lib,bin}" && bash -c "cp -r binaryen/main_64bit_binaryen/{lib,bin} upstream"

RUN mv node/24.6.0-linux-x64 node/24.6.0_64bit
RUN echo "node-24.6.0-64bit" > node/24.6.0_64bit/.emsdk_version


# wtf??

# configuraion
RUN ./emsdk activate ${EMSDK_VERSION} \
    && chmod 777 upstream/emscripten \
    && chmod -R 777 upstream/emscripten/cache \
    && echo "int main() { return 0; }" > hello.c \
    && upstream/emscripten/emcc -c hello.c \
    && cat upstream/emscripten/cache/sanity.txt \
    && rm hello.c

# optimization
# Cleanup Emscripten installation and strip some symbols
RUN . ./emsdk_env.sh \
    && strip -s `which node` \
    && rm -fr upstream/emscripten/tests \
    && find upstream/bin -type f -exec strip -s {} + || true


FROM ubuntu:jammy AS stage_deploy

RUN apt-get -qq -y update \
    # Somewhere in here apt sets up tzdata which asks for your time zone and blocks
    # waiting for the answer which you can't give as docker build doesn't read from
    # the terminal. The env vars set here avoid the interactive prompt and set the TZ.
    && DEBIAN_FRONTEND="noninteractive" TZ="America/San_Francisco" apt-get -qq install -y --no-install-recommends \
        sudo \
        libxml2 \
        ca-certificates \
        python3 \
        python3-pip \
        wget \
        curl \
        zip \
        unzip \
        git \
        git-lfs \
        ssh-client \
        build-essential \
        make \
        ant \
        libidn12 \
        cmake \
        openjdk-11-jre-headless \
    # Standard Cleanup on Debian images
    && apt-get -y clean \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/debconf/*-old \
    && rm -rf /usr/share/doc/* \
    && rm -rf /usr/share/man/?? \
    && rm -rf /usr/share/man/??_*

RUN apt-get -qq -y update && \
    apt-get -qq install -y --no-install-recommends sudo && \
    groupadd --gid 1000 zb3 \
    && useradd --uid 1000 --gid zb3 --shell /bin/bash --create-home zb3 && \
    apt-get install -y sudo && \
    echo 'zb3:rocks' | chpasswd && \
    gpasswd --add zb3 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


COPY --from=stage_build /emsdk /emsdk

# These fallback environment variables are intended for situations where the
# entrypoint is not utilized (as in a derived image) or overridden (e.g. when
# using `--entrypoint /bin/bash` in CLI).
# This corresponds to the env variables set during: `source ./emsdk_env.sh`
ENV EMSDK=/emsdk \
    PATH="/emsdk:/emsdk/upstream/emscripten:/emsdk/node/24.6.0_64bit/bin:${PATH}"

ENTRYPOINT ["/emsdk/docker/entrypoint.sh"]

