FROM ubuntu:jammy AS stage_build

RUN apt-get -qq -y update \
    && apt-get -qq install -y --no-install-recommends \
        binutils \
        build-essential \
        ca-certificates \
        file \
        git \
        python3 \
        python3-pip \
        cmake

WORKDIR /emsdk
ARG EMSDK_VERSION=4.0.12

RUN git clone --depth 1 --branch ${EMSDK_VERSION} https://github.com/emscripten-core/emsdk.git /emsdk

RUN ./emsdk install ${EMSDK_VERSION}

RUN ./emsdk install binaryen-main-64bit

COPY ./asyncify-eh-support.patch .

RUN patch -d binaryen/main -p1 <asyncify-eh-support.patch

RUN cd /emsdk/binaryen/main_64bit_binaryen/ && cmake --build . --config Release -- -j4
RUN bash -c "chown -R 1000:1000 binaryen/main_64bit_binaryen/{lib,bin}" && bash -c "cp -r binaryen/main_64bit_binaryen/{lib,bin} upstream"

# configuraion
RUN ./emsdk activate ${EMSDK_VERSION} \
    && chmod 777 upstream/emscripten \
    && chmod -R 777 upstream/emscripten/cache \
    && echo "int main() { return 0; }" > hello.c \
    && upstream/emscripten/emcc -c hello.c \
    && cat upstream/emscripten/cache/sanity.txt \
    && rm hello.c

# optimization
# Cleanup Emscripten installation and strip some symbols
RUN . ./emsdk_env.sh \
    && strip -s `which node` \
    && rm -fr upstream/emscripten/tests \
    && find upstream/bin -type f -exec strip -s {} + || true


FROM ubuntu:jammy AS stage_deploy

RUN apt-get -qq -y update \
    # Somewhere in here apt sets up tzdata which asks for your time zone and blocks
    # waiting for the answer which you can't give as docker build doesn't read from
    # the terminal. The env vars set here avoid the interactive prompt and set the TZ.
    && DEBIAN_FRONTEND="noninteractive" TZ="America/San_Francisco" apt-get -qq install -y --no-install-recommends \
        sudo \
        libxml2 \
        ca-certificates \
        python3 \
        python3-pip \
        wget \
        curl \
        zip \
        unzip \
        git \
        git-lfs \
        ssh-client \
        build-essential \
        make \
        ant \
        libidn12 \
        cmake \
        openjdk-11-jre-headless \
    # Standard Cleanup on Debian images
    && apt-get -y clean \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/debconf/*-old \
    && rm -rf /usr/share/doc/* \
    && rm -rf /usr/share/man/?? \
    && rm -rf /usr/share/man/??_*

RUN apt-get -qq -y update && \
    apt-get -qq install -y --no-install-recommends sudo && \
    groupadd --gid 1000 zb3 \
    && useradd --uid 1000 --gid zb3 --shell /bin/bash --create-home zb3 && \
    apt-get install -y sudo && \
    echo 'zb3:rocks' | chpasswd && \
    gpasswd --add zb3 sudo && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


COPY --from=stage_build /emsdk /emsdk

# These fallback environment variables are intended for situations where the
# entrypoint is not utilized (as in a derived image) or overridden (e.g. when
# using `--entrypoint /bin/bash` in CLI).
# This corresponds to the env variables set during: `source ./emsdk_env.sh`
ENV EMSDK=/emsdk \
    PATH="/emsdk:/emsdk/upstream/emscripten:/emsdk/node/22.16.0_64bit/bin:${PATH}"

ENTRYPOINT ["/emsdk/docker/entrypoint.sh"]


# npm install?
# what actually copies stuff?

# from source to build dir?
#   # Deploy scripts needed from source repository to build directory
#   remove_tree(os.path.join(build_root, 'scripts'))
#   shutil.copytree(os.path.join(src_root, 'scripts'), os.path.join(build_root, 'scripts'))
#   remove_tree(os.path.join(build_root, 'src', 'js'))
#   shutil.copytree(os.path.join(src_root, 'src', 'js'), os.path.join(build_root, 'src', 'js'))


# docker build --progress=plain -t custom-emsdk . -f Dockerfile.btest

# docker cp $(docker create --name temp_container custom-emsdk):/emsdk/binaryen/main/src/passes/Asyncify.cpp . && docker rm temp_container



# # This generates configuration that contains all valid paths according to installed SDK
# # TODO(sbc): We should be able to use just emcc -v here but it doesn't
# # currently create the sanity file.
# RUN cd ${EMSDK} \
#     && echo "## Generate standard configuration" \
#     && ./emsdk activate ${EMSCRIPTEN_VERSION} \
#     && chmod 777 ${EMSDK}/upstream/emscripten \
#     && chmod -R 777 ${EMSDK}/upstream/emscripten/cache \
#     && echo "int main() { return 0; }" > hello.c \
#     && ${EMSDK}/upstream/emscripten/emcc -c hello.c \
#     && cat ${EMSDK}/upstream/emscripten/cache/sanity.txt \
#     && echo "## Done"

# # Cleanup Emscripten installation and strip some symbols
# RUN echo "## Aggressive optimization: Remove debug symbols" \
#     && cd ${EMSDK} && . ./emsdk_env.sh \
#     # Remove debugging symbols from embedded node (extra 7MB)
#     && strip -s `which node` \
#     # Tests consume ~80MB disc space
#     && rm -fr ${EMSDK}/upstream/emscripten/tests \
#     # strip out symbols from clang (~extra 50MB disc space)
#     && find ${EMSDK}/upstream/bin -type f -exec strip -s {} + || true \
#     && echo "## Done"

#ENV EMSDK=/emsdk \
#    PATH="/emsdk:/emsdk/upstream/emscripten:/emsdk/node/22.16.0_64bit/bin:${PATH}"

# FROM ubuntu:jammy AS stage_deploy

# COPY --from=stage_build /emsdk /emsdk

# # These fallback environment variables are intended for situations where the
# # entrypoint is not utilized (as in a derived image) or overridden (e.g. when
# # using `--entrypoint /bin/bash` in CLI).
# # This corresponds to the env variables set during: `source ./emsdk_env.sh`
# ENV EMSDK=/emsdk \
#     PATH="/emsdk:/emsdk/upstream/emscripten:/emsdk/node/22.16.0_64bit/bin:${PATH}"

# # ------------------------------------------------------------------------------
# # Create a 'standard` 1000:1000 user
# # Thanks to that this image can be executed as non-root user and created files
# # will not require root access level on host machine Please note that this
# # solution even if widely spread (i.e. Node.js uses it) is far from perfect as
# # user 1000:1000 might not exist on host machine, and in this case running any
# # docker image will cause other random problems (mostly due `$HOME` pointing to
# # `/`)
# RUN echo "## Create emscripten user (1000:1000)" \
#     && groupadd --gid 1000 emscripten \
#     && useradd --uid 1000 --gid emscripten --shell /bin/bash --create-home emscripten \
#     && echo "## Done"

# # ------------------------------------------------------------------------------

# RUN echo "## Update and install packages" \
#     && apt-get -qq -y update \
#     # Somewhere in here apt sets up tzdata which asks for your time zone and blocks
#     # waiting for the answer which you can't give as docker build doesn't read from
#     # the terminal. The env vars set here avoid the interactive prompt and set the TZ.
#     && DEBIAN_FRONTEND="noninteractive" TZ="America/San_Francisco" apt-get -qq install -y --no-install-recommends \
#         sudo \
#         libxml2 \
#         ca-certificates \
#         python3 \
#         python3-pip \
#         wget \
#         curl \
#         zip \
#         unzip \
#         git \
#         git-lfs \
#         ssh-client \
#         build-essential \
#         make \
#         ant \
#         libidn12 \
#         cmake \
#         openjdk-11-jre-headless \
#     # Standard Cleanup on Debian images
#     && apt-get -y clean \
#     && apt-get -y autoclean \
#     && apt-get -y autoremove \
#     && rm -rf /var/lib/apt/lists/* \
#     && rm -rf /var/cache/debconf/*-old \
#     && rm -rf /usr/share/doc/* \
#     && rm -rf /usr/share/man/?? \
#     && rm -rf /usr/share/man/??_* \
#     && echo "## Done"